name: endpoint_update_and_cleanup_on_merge

on:
  push:
    branches:
      - main
    paths:
      - 'machine-learning/**'
  workflow_dispatch:
    inputs:
      product_categories:
        description: Product categories
        required: true


jobs:
  update-prod-and-remove-PR-endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is required to fetch all commits

      - name: Determine Categories
        id: get-categories
        working-directory: machine-learning/src        
        shell: bash -l {0}
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            files=$(git diff --name-only ${{ github.event.before }} HEAD)
            echo "Modified files: $files"  # Log the files variable

            echo "$files" | python compute_categories_for_automatic_endpoint_updates.py
            categories="$(echo "$files" | python compute_categories_for_automatic_endpoint_updates.py)"
          fi

          if [[ -z "$categories" ]]; then
            echo "No changes detected to the special folders."
            echo "categories=" >> $GITHUB_OUTPUT # set an empty output for clarity
          else
            echo "Using categories: "$categories""
            echo "categories="$categories"" >> $GITHUB_OUTPUT
          fi

          echo hey: "${{ github.ref }}"
          echo buddy: "${{ github.ref_name }}"

          # Determine BRANCH_NAME based on event type
          if [[ "${{ github.event_name }}" == "push" ]]; then
            COMMIT_HASH_OF_BRANCH_PARENT=$(git log --merges -n 1 --pretty=format:"%P" | cut -d ' ' -f 2)
            BRANCH_NAME=$(git branch --contains $COMMIT_HASH_OF_BRANCH_PARENT | grep -v '^\* main$')
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            BRANCH_NAME=${{ github.ref_name }}
          fi
          echo Branch name: "${BRANCH_NAME}"
          