name: endpoint_update_and_cleanup_on_merge

on:
  push:
    branches:
      - main
    paths:
      - 'machine-learning/**'
  workflow_dispatch:
    inputs:
      product_categories:
        description: Product categories
        required: true


jobs:
  update-prod-and-remove-PR-endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is required to fetch all commits

      - name: Determine Categories
        id: get-categories
        working-directory: machine-learning/src        
        shell: bash -l {0}
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            files=$(git diff --name-only ${{ github.event.before }} HEAD)
            echo "Modified files: $files"  # Log the files variable

            echo "$files" | python compute_categories_for_automatic_endpoint_updates.py
            categories="$(echo "$files" | python compute_categories_for_automatic_endpoint_updates.py)"
          fi

          if [[ -z "$categories" ]]; then
            echo "No changes detected to the special folders."
            echo "categories=" >> $GITHUB_OUTPUT # set an empty output for clarity
          else
            echo "Using categories: "$categories""
            echo "categories="$categories"" >> $GITHUB_OUTPUT
          fi

          echo hey: "${{ github.ref }}"
          echo buddy: "${{ github.ref_name }}"

          # Determine BRANCH_NAME based on event type
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # This code is uglier than you'd expect because the old branch gets deleted BEFORE the push event
            # so we have to do some gymnastics. There is probably a better way to do this.

            COMMIT_HASH_OF_BRANCH_TIP=$(git log --merges -n 1 --pretty=format:"%P" | cut -d ' ' -f 2)
            echo Commit hash of the tip of the branch being merged into main: "$COMMIT_HASH_OF_BRANCH_TIP"
            
            # Get the name of all branches containing the tip, e.g. remotes/origin/main and remotes/origin/some-branch
            # This should (I think) always be exactly two branches assuming we're not doing an octopus merge,
            # specifically the two branches will be main and whatever the other branch was
            BRANCHES_CONTAINING_TIP=$(git branch -a --contains $COMMIT_HASH_OF_BRANCH_TIP)
            echo Branches that contain tip: "$BRANCHES_CONTAINING_TIP"
            
            # Extract the branch name, excluding 'main', yes I had GPT write the awk for me
            BRANCH_NAME=$(echo "$BRANCHES_CONTAINING_TIP" | grep -v "main" | awk -F'/' '{print $NF}')
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            BRANCH_NAME=${{ github.ref_name }}
          fi
          echo Branch name: "${BRANCH_NAME}"
          