name: endpoint_update_and_cleanup_on_merge

on:
  push:
    branches:
      - main
    paths:
      - 'machine-learning/**'
  workflow_dispatch:
    inputs:
      product_categories:
        description: Product categories
        required: true


jobs:
  update-prod-and-remove-PR-endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is required to fetch all commits

      - name: Determine Categories
        id: get-categories
        working-directory: machine-learning/src        
        shell: bash -l {0}
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            files=$(git diff --name-only ${{ github.event.before }} HEAD)
            echo "Modified files: $files"  # Log the files variable

            files2=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
            echo "Modified files attempt 2: $files2"  # Log the files variable

            files3=$(git diff --name-only ${{ github.event.base_ref }} ${{ github.sha }})
            echo "Modified files attempt 3: $files3"  # Log the files variable

            files4=$(git diff --name-only ${{ github.event.base_ref }} HEAD)
            echo "Modified files attempt 4: $files4"  # Log the files variable

            echo "github.sha: ${{ github.sha }}"
            echo "github.event.before: ${{ github.event.before }}"                        
            echo "github.event.base_ref: ${{ github.event.base_ref }}"

            echo "$files" | python compute_categories_for_automatic_endpoint_updates.py
            categories="$(echo "$files" | python compute_categories_for_automatic_endpoint_updates.py)"
          fi

          if [[ -z "$categories" ]]; then
            echo "No changes detected to the special folders."
            echo "categories=" >> $GITHUB_OUTPUT # set an empty output for clarity
          else
            echo "Using categories: "$categories""
            echo "categories="$categories"" >> $GITHUB_OUTPUT
          fi
          