name: endpoint_update_on_push

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'machine-learning/**'
  workflow_dispatch:
    inputs:
      product_categories:
        description: Product categories
        required: true


jobs:
  update-prod-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed so we can go all the way back until before the push
                         # which could be any depth

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: machine-learning
            use-mamba: true

      - uses: actions/cache@v3
        env:
          cache-name: cache-conda-environment   
        with:
          path: /usr/share/miniconda3/envs/machine-learning
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('machine-learning/environment.yml') }}
        id: cache                    

      - name: Update environment
        run: mamba env update -n machine-learning -f machine-learning/environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Determine Categories
        id: get-categories
        working-directory: machine-learning/src
        shell: bash -l {0}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            categories="${{ github.event.inputs.product_categories }}"
          else
            files=$(git diff --name-only ${{ github.event.before }} HEAD)
            echo "Modified files: $files"  # Log the files variable
            categories="$(echo "$files" | python github/compute_categories_for_automatic_endpoint_updates.py)"
          fi

          if [[ -z "$categories" ]]; then
            echo "No changes detected that would require model training or PR endpoint deployment"
            echo "categories=" >> $GITHUB_OUTPUT # set an empty output for clarity
          else
            echo "Using categories: "$categories""
            echo "categories="$categories"" >> $GITHUB_OUTPUT
          fi